### ISSUE TITLE
關於line這邊的對接窗口問題

### ISSUE THREAD

**Issue by dan0618x** [HappyGroupHub/Discord-Line-Message-Sync#10]
Hi LD 您好：
   非常感謝您開發了這樣一套系統，真的非常厲害！
   想請教您，目前這套系統是在對接line的群組部分，不知道他有沒有辦法對接社群或者是官方帳號呢？因為目前有這方面的需求，屬於單方面訊息通知的用途。
   若您能答覆，我備感榮幸！再次感謝您～

**Comment by dan0618x** [comment]
我想是不是因為line notify 目前只支援社群呢？

**Comment by HappyGroupHub** [comment]
是的，因為 Line Notify 目前只有支援個人通知以及群組通知
官方帳號或社群皆無法使用喔🥲
