### ISSUE TITLE
請教問題

### ISSUE THREAD

**Issue by eggeggdog** [HappyGroupHub/Discord-Line-Message-Sync#11]
步驟做好之後，Line發送 !綁定 沒有回應

附檔為設定檔與執行的視窗

[config.txt](https://github.com/user-attachments/files/16177406/config.txt)
![line_bot](https://github.com/HappyGroupHub/Discord-Line-Message-Sync/assets/26154029/1629e9a4-9254-41a8-b19a-aa377090a366)
![discord_bot](https://github.com/HappyGroupHub/Discord-Line-Message-Sync/assets/26154029/0008438e-c7e5-47c4-a2a0-033b65a2939c)

**Comment by HappyGroupHub** [comment]
請問你是否有正確填入 LINE BOT 設定頁面中的 webhook 連結？
設定好之後網站上也可以進行測試喔，如果收到OK就代表有測試成功

**Comment by HappyGroupHub** [comment]
Closed with no response.
