### ISSUE TITLE
獲取 Line group ID 問題

### ISSUE THREAD

**Issue by tear670103** [HappyGroupHub/Discord-Line-Message-Sync#3]
我照著做到獲取 Line group ID那
channel_access_token、channel_secret都填了
也運行 run.bat了
然後在想要同步的群組內傳送 !ID
line bot回我 
Thanks for your message!

Unfortunately, this account isn't set up to reply directly to messages.
Stay tuned for our next message (moon smile)

我做錯了哪裡了嗎?

**Comment by HappyGroupHub** [comment]
嗨!
根據你的問題我想你可能走錯repo了!
你詢問的問題應該是在此專案 [Discord Line 訊息同步機器人](https://github.com/HappyGroupHub/Discord-Line-Message-Sync)

此專案-[以太坊錢包交易通知機器人](https://github.com/HappyGroupHub/Ethereum-Wallet-Tracker)不會使用到Line bot進行通知
而是使用Line Notify進行通知服務

如果確定是回報錯專案的話可以留言跟我說一聲
我會將此回報轉至該專案並在那裡一併回覆你!

**Comment by tear670103** [comment]
抱歉，我走錯了

**Comment by HappyGroupHub** [comment]
這個問題會發生好像是因為沒有關掉Line bot預設的自動回覆功能
你可以到[Line Developers](https://developers.line.biz/console/)調整這個設定
選擇你的bot之後點進Messaging API, 往下滑到 LINE Official Account features 
找到Auto-reply messages後點擊Edit進行關閉

如圖:
![圖片](https://github.com/HappyGroupHub/Discord-Line-Message-Sync/assets/43276256/32d9423e-c3ea-4e36-a819-33f7d9dd1843)

**Comment by tear670103** [comment]
也沒辦法
LINE BOT沒回訊息

**Comment by HappyGroupHub** [comment]
理解 那你應該是沒有執行到這兩個步驟

- [設定Line Webhook](https://github.com/HappyGroupHub/Discord-Line-Message-Sync#%E8%A8%AD%E5%AE%9Aline-webhook)
- [使用Ngrok以符合HTTPS協議](https://github.com/HappyGroupHub/Discord-Line-Message-Sync#%E4%BD%BF%E7%94%A8ngrok%E4%BB%A5%E7%AC%A6%E5%90%88https%E5%8D%94%E8%AD%B0)

我README.md教學的排序可能有問題讓你沒意識到
你要完成這兩個設定後，使用run.bat後才可使用!

**Comment by tear670103** [comment]
在 使用Ngrok以符合HTTPS協議 那邊時
Fowarding 所生成的URL
用瀏覽器進去會顯示錯誤

ERR_NGROK_8012 Traffic was successfully tunneled to the ngrok agent, but the agent failed to establish a connection to the upstream web service at localhost:5000. The error encountered was: dial tcp [::1]:5000: connectex: No connection could be made because the target machine actively refused it.

之後在 設定Line Webhook 那邊時
Webhook URL設 <Fowarding 所生成的URL>/calback
按verify會顯示 A timeout occurred when sending a webhook event objec

---------------------------------------------------------------------------------------------------------------
不知為何 又按一次 就成功了

**Comment by HappyGroupHub** [comment]
所以目前是成功的嗎(?

**Comment by tear670103** [comment]
是的，謝謝

**Comment by HappyGroupHub** [comment]
太好了! 那祝您使用愉快~
有任何問題一樣都可以在這裡發問告訴我喔~
(或有任何想要我更新的也行哈哈
你們的使用是我持續製作此專案的動力!
