### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by ray1025** [HappyGroupHub/Discord-Line-Message-Sync#5]
Is the latest version 0.1.5 available with the source code? I need it for use on a Linux system. Thank you.

**Comment by HappyGroupHub** [comment]
Yes, you definitely can download the source code from any [release page](https://github.com/HappyGroupHub/Discord-Line-Message-Sync/releases)! Simply click the "Source Code (zip)" as the selection, or simply click [here](https://github.com/HappyGroupHub/Discord-Line-Message-Sync/archive/refs/tags/v0.1.5.zip) if you can't find it.

After all the source codes have been downloaded, run both `discord_bot.py` and `line_bot.py`, these two files are the main files of the program, DON'T close them! And make sure you have your webhook endpoints set with reverse proxy, which it should startswith `https://`, if you find it hard to achieve, try using `Ngrok`'s service, you can find a simple tutorial [here](https://github.com/HappyGroupHub/Discord-Line-Message-Sync#use-ngrok-to-create-a-reverse-proxy).

GL!

**Comment by ray1025** [comment]
I understand. I've been using it on a Linux system since version 0.1.4, and everything has been working fine. I noticed your recent update to version 0.1.5 a few days ago and thought that the Python version might also be updated, which is why I inquired. Thank you very much for developing this project.

**Comment by HappyGroupHub** [comment]
Also a big pleasure for me to having you guys enjoying using it!
So, is your problem solved? Since you mentioned that `v0.1.4` do work fine but the `v0.1.5` do crash or sth? I mean it's working equally fine here on my windows system with the update. If you do have any problems, feel free to report here! or if the task has been solved you can also share it here! I'm always glad to help.

**Comment by ray1025** [comment]
Everything is currently functioning properly. Yesterday, I just noticed that the .zip file and the source code had different dates, so I just wanted to confirm that's all.
