### ISSUE TITLE
sync_channels.json

### ISSUE THREAD

**Issue by ray1025** [HappyGroupHub/Discord-Line-Message-Sync#6]
May I ask if [utilities.py](https://github.com/HappyGroupHub/Discord-Line-Message-Sync/blob/48cfcefe83fe6fb058eeafb5c114fde65e5aa3d0/utilities.py) is missing the capability to create and manage the sync_channels.json file?

**Comment by HappyGroupHub** [comment]
Please do not update your program if there’s no new release. Use the latest version 0.1.5 instead, thanks 🙏 
Those update in master branch are still in development.

**Comment by ray1025** [comment]
Okay, I understand. Thank you for your hard work!
