### ISSUE TITLE
discord video cannot be sent to line

### ISSUE THREAD

**Issue by Jj088456** [HappyGroupHub/Discord-Line-Message-Sync#7]

**Comment by HappyGroupHub** [comment]
Hi @Jj088456 ,

Discord video to Line has now only supported `.mp4` files only, please make sure the video file you're syncing is in MP4 format, and also under 200MB.

I'll soon make it more format supported when I have time, any PR is also welcomed!

**Comment by Jj088456** [comment]
我是傳mp4格式也小於200MB，是用你做好的機器人!

**Comment by Jj088456** [comment]
還想請問 能夠多群同步嗎?

**Comment by HappyGroupHub** [comment]
1. 了解，可以請你上傳該影片給我嗎? 這樣方便我進行測試 謝謝
2. 目前不支援喔！ 專案目前更新速度很慢，主要以維護為主。歡迎任何大神一起維護~
另：**[已完成維護]** ~~目前我協助架設的服務正在硬體維護，所以近期都不會提供服務~~

**Comment by HappyGroupHub** [comment]
Hi @Jj088456 ,

有任何更新的話歡迎在這裡留言喔!
因長時間無收到任何回應，已暫時將此 Issue 關閉
