### ISSUE TITLE
 Custom subdomains are a feature on ngrok's paid plans

### ISSUE THREAD

**Issue by twmht** [HappyGroupHub/Discord-Line-Message-Sync#8]
按照文件跑 ngrok 的時候出現

```
ngrok start app
```

Custom subdomains are a feature on ngrok's paid plans

這是步驟有錯還是 ngrok 的 policy 有變?

**Comment by HappyGroupHub** [comment]
確認了一下 Ngrok 的 policy 沒有變更
可能是您在設定上有些誤會~ 希望你使用愉快!
