### ISSUE TITLE
line社群無法使用

### ISSUE THREAD

**Issue by beifen8778** [HappyGroupHub/Discord-Line-Message-Sync#9]
請問一下line notify和訊息同步機器人是不是不能邀請到line社群(line OpenChat),我試過無法邀請加入,使用群組可以正常邀請

**Comment by HappyGroupHub** [comment]
是的，LINE 社群目前不開放加入任何機器人喔
這部分要等 LINE 更新才有辦法實作，不然我也很想這樣做 XD
